[package]
name = "nombre-del-proyecto"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.76"
yew = "0.18.0"
yew-router = "0.11.0"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3.55"
features = ["console"]
